name: course-project-consortium-website

services:
  db:
    image: ${POSTGRES_IMAGE:-postgres:17}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    image: consortium-backend:${VERSION:?}
    env_file:
      - ./Backend/.env
    environment:
      DB_HOST: db
    ports:
      - "${BACKEND_PORT:-5000}:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

  frontend:
    image: consortium-frontend:${VERSION:?}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - web
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge

