upstream backend {
  zone backend 64k;
  resolver 127.0.0.11 valid=5s ipv6=off;
  server web:80 resolve;
}

server {
  listen 80;

  location / {
    root /app;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://backend;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /admin {
    proxy_pass http://backend;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
