"""Second migration

Revision ID: 95d18c753772
Revises: b48dba1e160b
Create Date: 2025-01-21 14:03:19.223138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d18c753772'
down_revision = 'b48dba1e160b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('news_magazine_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'magazine', ['magazine_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('news_authors', schema=None) as batch_op:
        batch_op.drop_constraint('news_authors_news_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('news_authors_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'news', ['news_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('authors')

    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.drop_constraint('publication_authors_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('publication_authors_publication_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'publications', ['publication_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint('publications_magazine_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'magazine', ['magazine_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publications_magazine_id_fkey', 'magazine', ['magazine_id'], ['id'])

    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_authors_publication_id_fkey', 'publications', ['publication_id'], ['id'])
        batch_op.create_foreign_key('publication_authors_author_id_fkey', 'author', ['author_id'], ['id'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    with op.batch_alter_table('news_authors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('news_authors_author_id_fkey', 'author', ['author_id'], ['id'])
        batch_op.create_foreign_key('news_authors_news_id_fkey', 'news', ['news_id'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('news_magazine_id_fkey', 'magazine', ['magazine_id'], ['id'])

    # ### end Alembic commands ###
