"""Initial migration

Revision ID: b48dba1e160b
Revises: 
Create Date: 2025-01-21 12:36:35.059640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48dba1e160b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magazine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'magazine', ['magazine_id'], ['id'])
        batch_op.drop_column('authors')
        batch_op.drop_column('magazine')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magazine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'magazine', ['magazine_id'], ['id'])
        batch_op.drop_column('authors')
        batch_op.drop_column('magazine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magazine', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('magazine_id')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magazine', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('magazine_id')

    # ### end Alembic commands ###
