name: Pytest
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Python 3.12 and PostgreSQL 17
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from tests
      - name: Remove test database
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
